
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS SITE;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS MEMBERS;
DROP TABLE IF EXISTS DIST;
DROP TABLE IF EXISTS TRANSACTION_HISTORY;
DROP TABLE IF EXISTS BANKS;

CREATE TABLE ROLES (
    ROLE_NAME VARCHAR(50) NOT NULL PRIMARY KEY COMMENT '역할 명'
);

-- 각 사이트 회원
CREATE TABLE MEMBERS (
    MID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 고유번호',
    MEMBER_ID VARCHAR(50) NOT NULL COMMENT '사용자 ID',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '비밀번호',
    -- USER_NAME VARCHAR(50) NOT NULL COMMENT '사용자 이름',
    -- EMAIL VARCHAR(50) NOT NULL COMMENT '이메일 주소',
    PHONE VARCHAR(20) NOT NULL COMMENT '전화번호',
    BANK_NAME VARCHAR(100) NOT NULL COMMENT '사용자 은행 명',
    BANK_CODE VARCHAR(10) COMMENT '은행코드',
    BANK_ACCOUNT VARCHAR(100) NOT NULL COMMENT '사용자 계좌번호',
    BANK_ACCOUNT_HOLDER VARCHAR(50) NOT NULL COMMENT '출금은행 예금주명',
    BANK_IDENTIFIER VARCHAR(10) NOT NULL COMMENT '개인 : 생년월일 6자, 사업자 : 사업자 등록번호',
    DEPOSIT_BANK_NAME VARCHAR(100) COMMENT '가상계좌 입금은행 명',
    DEPOSIT_BANK_CODE VARCHAR(10) COMMENT '가상계좌 은행코드',
    DEPOSIT_BANK_ACCOUNT VARCHAR(100) COMMENT '가상계좌 계좌번호',
    DEPOSIT_BANK_ACCOUNT_PERIOD_FROM TIMESTAMP COMMENT '가상계좌 사용 시작기간',
    DEPOSIT_BANK_ACCOUNT_PERIOD_TO TIMESTAMP COMMENT '가상계좌 사용 만료기간',
    DIST_ID BIGINT COMMENT '총판 ID',
    SITE_ID BIGINT COMMENT '가맹점 ID',
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성(출금가능)/비활성(출금불가) 유저 여부 - 출금가능 여부와 같다',
    DELETED BOOLEAN NOT NULL DEFAULT FALSE COMMENT '삭제유저 여부',
    REG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '마지막 변경일',
    DEL_DATE TIMESTAMP NULL DEFAULT NULL COMMENT '삭제일',

    -- 복합 유니크 제약 조건 추가
    UNIQUE KEY UNIQUE_USER_KEY (MEMBER_ID, DIST_ID, SITE_ID)
);

-- 본사, 총판, 사이트 매니저들 테이블
CREATE TABLE USERS (
    UID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '매니저 고유번호',
    USER_ID VARCHAR(50) NOT NULL COMMENT '매니저 ID',
    USER_NAME VARCHAR(50) NOT NULL COMMENT '사용자 이름',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '비밀번호',
    EMAIL VARCHAR(50) NOT NULL COMMENT '이메일 주소',
    PHONE VARCHAR(20) NOT NULL COMMENT '전화번호',
    BANK_NAME VARCHAR(100) NOT NULL COMMENT '총판, 가맹점 은행 명',
    BANK_CODE VARCHAR(10) COMMENT '은행코드',
    BANK_ACCOUNT VARCHAR(100) NOT NULL COMMENT '사용자 계좌번호',
    BANK_ACCOUNT_HOLDER VARCHAR(100) NOT NULL COMMENT '출금은행 예금주명',
    BANK_IDENTIFIER VARCHAR(50) NOT NULL COMMENT '개인 : 생년월일 6자, 회사 : 사업자 등록번호',
    DIST_ID BIGINT COMMENT '총판 ID, 없으면 본사 매니저이다',
    SITE_ID BIGINT COMMENT '가맹점 ID, 없으면 본사 매니저이거나 총판 매니저이다',
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성/비활성 매니저 여부',
    REG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '마지막 변경일',
    PASSWORD_CHANGED_DATE TIMESTAMP NULL DEFAULT NULL COMMENT '비밀번호 변경일',

    -- 복합 유니크 제약 조건 추가
    UNIQUE KEY UNIQUE_USER_KEY (USER_ID, DIST_ID, SITE_ID)
);

CREATE TABLE USER_ROLES (
    USER_UNIQUE_ID BIGINT NOT NULL COMMENT '사용자 고유번호',
    ROLE_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (USER_UNIQUE_ID, ROLE_NAME),
    FOREIGN KEY (USER_UNIQUE_ID) REFERENCES USERS(UID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_NAME) REFERENCES ROLES(ROLE_NAME) ON DELETE CASCADE
);

CREATE TABLE DIST (
    DIST_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '총판 고유번호',
    NAME VARCHAR(50) NOT NULL COMMENT '총판 이름',
    COMM_RATE DECIMAL(5,2) NOT NULL COMMENT '본사에 대한 총판 수수료',
    EMAIL VARCHAR(50) NOT NULL COMMENT '이메일',
    PHONE VARCHAR(20) NOT NULL COMMENT '전화번호',
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성 여부',
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    UPD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    DEL_DATE TIMESTAMP NULL COMMENT '삭제일'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=101;


CREATE TABLE SITE (
    SITE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '가맹점 고유번호',
    DIST_ID BIGINT NOT NULL COMMENT '총판 ID',
    NAME VARCHAR(50) NOT NULL COMMENT '가맹점 이름',
    COMM_RATE DECIMAL(5,2) NOT NULL COMMENT '총판에 대한 가맹점 수수료',
    EMAIL VARCHAR(50) NOT NULL COMMENT '이메일',
    PHONE VARCHAR(20) NOT NULL COMMENT '전화번호',
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE COMMENT '가맹점 활성 여부',
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    UPD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    DEL_DATE TIMESTAMP NULL COMMENT '삭제일',
    CONSTRAINT FK_SITE_DIST FOREIGN KEY (DIST_ID) REFERENCES DIST(DIST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1001;


CREATE TABLE TRANSACTION_HISTORY (
    TID BIGINT NOT NULL AUTO_INCREMENT COMMENT '고유번호',
    TYPE VARCHAR(20) NOT NULL COMMENT 'DEPOSIT, WITHDRAWAL',
    MEMBER_ID VARCHAR(50) NOT NULL COMMENT '입금자 ID',
    MEMBER_NAME VARCHAR(50) COMMENT '입금자명. PG에서 넣어줌',
    AMOUNT DECIMAL(15,2) NOT NULL COMMENT '충전금액, 출금금액',
    WITHDRAWAL_BANK_NAME VARCHAR(100) COMMENT '출금은행 명',
    WITHDRAWAL_BANK_CODE VARCHAR(10) COMMENT '출금 은행코드',
    WITHDRAWAL_BANK_ACCOUNT VARCHAR(100) COMMENT '출금자 계좌번호',
    WITHDRAWAL_BANK_ACCOUNT_HOLDER VARCHAR(100) COMMENT '출금은행 예금주명',
    WITHDRAWAL_BANK_IDENTIFIER VARCHAR(50) COMMENT '개인 : 생년월일 6자, 회사 : 사업자 등록번호',
    WITHDRAWAL_DATE TIMESTAMP COMMENT '출금 날짜 시간',
    WITHDRAWAL_STATUS VARCHAR(10) COMMENT '출금요청 상태 : NEW, CONFIRMED',
    DEPOSIT_PAYMENT_ID VARCHAR(50) COMMENT 'PAYMENT 고유번호',
    DEPOSIT_PAYMENT_COMPANY_ID VARCHAR(50) COMMENT 'PAYMENT 회사 고유번호',
    DEPOSIT_BANK_NAME VARCHAR(100) COMMENT '가상계좌 입금은행 명',
    DEPOSIT_BANK_CODE VARCHAR(10) COMMENT '가상계좌 은행코드',
    DEPOSIT_BANK_ACCOUNT VARCHAR(100) COMMENT '가상계좌 계좌번호',
    DEPOSIT_BANK_ACCOUNT_PERIOD_FROM TIMESTAMP COMMENT '가상계좌 사용 시작기간',
    DEPOSIT_BANK_ACCOUNT_PERIOD_TO TIMESTAMP COMMENT '가상계좌 사용 만료기간',
    DEPOSIT_DATE TIMESTAMP COMMENT '가상계좌 입금날짜 시간',
    DIST_ID BIGINT COMMENT '총판 ID, member, 가맹점, 총판 모두 기록됨',
    DIST_COMM_RATE DECIMAL(5,2) COMMENT '현 시점 총판 수수료율',
    DIST_COMM_FEE DECIMAL(15,2) COMMENT '현 시점 총판 수수료',
    HQ_COMM_RATE DECIMAL(5,2) COMMENT '현 시점 본사 수수료율',
    HQ_COMM_FEE DECIMAL(15,2) COMMENT '본사 수수료',
    BALANCE DECIMAL(15,2) NOT NULL COMMENT '가맹점 잔여금액',
    SITE_ID BIGINT NOT NULL COMMENT '가맹점 ID',
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '송신받은 날짜',

    PRIMARY KEY (TID, SITE_ID),
    CHECK (type IN ('DEPOSIT', 'WITHDRAWAL'))
)
PARTITION BY LIST (SITE_ID) (
    PARTITION p1001 VALUES IN (1001),
    PARTITION p1002 VALUES IN (1002),
    PARTITION p1003 VALUES IN (1003),
    PARTITION p1004 VALUES IN (1004)
);

CREATE TABLE BANKS (
    CODE VARCHAR(10) PRIMARY KEY COMMENT '은행 코드',
    NAME VARCHAR(50) NOT NULL COMMENT '은행 이름'
);
